name: cv-demo
namespace: ${infra.kubernetes.namespace}

image: ${artifact.metadata.image}

env:
  config:
    # Override in environment with ingress controller load balancer IP or host
    # E.g http://a8241cbf8317f4c1ab5507fbce9d576c-671821569.us-east-2.elb.amazonaws.com:8080/
    ALLOWED_ORIGINS: http://ab45b3901f0574bfdac6c1c5754e183f-1241786145.us-east-1.elb.amazonaws.com:8080/
